version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: betwise
      POSTGRES_USER: betwise
      POSTGRES_PASSWORD: betwise123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U betwise"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: